// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct TerrainMetadataData {
  address occurenceAddress;
  bytes4 occurenceSelector;
}

library TerrainMetadata {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "TerrainMetadata", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746200000000000000000000000000005465727261696e4d6574616461746100);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0018020014040000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (address, bytes4)
  Schema constant _valueSchema = Schema.wrap(0x0018020061430000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "objectTypeId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "occurenceAddress";
    fieldNames[1] = "occurenceSelector";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config (using the specified store).
   */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get occurenceAddress.
   */
  function getOccurenceAddress(bytes32 objectTypeId) internal view returns (address occurenceAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get occurenceAddress.
   */
  function _getOccurenceAddress(bytes32 objectTypeId) internal view returns (address occurenceAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get occurenceAddress (using the specified store).
   */
  function getOccurenceAddress(IStore _store, bytes32 objectTypeId) internal view returns (address occurenceAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set occurenceAddress.
   */
  function setOccurenceAddress(bytes32 objectTypeId, address occurenceAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((occurenceAddress)), _fieldLayout);
  }

  /**
   * @notice Set occurenceAddress.
   */
  function _setOccurenceAddress(bytes32 objectTypeId, address occurenceAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((occurenceAddress)), _fieldLayout);
  }

  /**
   * @notice Set occurenceAddress (using the specified store).
   */
  function setOccurenceAddress(IStore _store, bytes32 objectTypeId, address occurenceAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    _store.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((occurenceAddress)), _fieldLayout);
  }

  /**
   * @notice Get occurenceSelector.
   */
  function getOccurenceSelector(bytes32 objectTypeId) internal view returns (bytes4 occurenceSelector) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes4(_blob));
  }

  /**
   * @notice Get occurenceSelector.
   */
  function _getOccurenceSelector(bytes32 objectTypeId) internal view returns (bytes4 occurenceSelector) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes4(_blob));
  }

  /**
   * @notice Get occurenceSelector (using the specified store).
   */
  function getOccurenceSelector(IStore _store, bytes32 objectTypeId) internal view returns (bytes4 occurenceSelector) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (bytes4(_blob));
  }

  /**
   * @notice Set occurenceSelector.
   */
  function setOccurenceSelector(bytes32 objectTypeId, bytes4 occurenceSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((occurenceSelector)), _fieldLayout);
  }

  /**
   * @notice Set occurenceSelector.
   */
  function _setOccurenceSelector(bytes32 objectTypeId, bytes4 occurenceSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((occurenceSelector)), _fieldLayout);
  }

  /**
   * @notice Set occurenceSelector (using the specified store).
   */
  function setOccurenceSelector(IStore _store, bytes32 objectTypeId, bytes4 occurenceSelector) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    _store.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((occurenceSelector)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 objectTypeId) internal view returns (TerrainMetadataData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 objectTypeId) internal view returns (TerrainMetadataData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data (using the specified store).
   */
  function get(IStore _store, bytes32 objectTypeId) internal view returns (TerrainMetadataData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = _store.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 objectTypeId, address occurenceAddress, bytes4 occurenceSelector) internal {
    bytes memory _staticData = encodeStatic(occurenceAddress, occurenceSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 objectTypeId, address occurenceAddress, bytes4 occurenceSelector) internal {
    bytes memory _staticData = encodeStatic(occurenceAddress, occurenceSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values (using the specified store).
   */
  function set(IStore _store, bytes32 objectTypeId, address occurenceAddress, bytes4 occurenceSelector) internal {
    bytes memory _staticData = encodeStatic(occurenceAddress, occurenceSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    _store.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 objectTypeId, TerrainMetadataData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.occurenceAddress, _table.occurenceSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 objectTypeId, TerrainMetadataData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.occurenceAddress, _table.occurenceSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct (using the specified store).
   */
  function set(IStore _store, bytes32 objectTypeId, TerrainMetadataData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.occurenceAddress, _table.occurenceSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    _store.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (address occurenceAddress, bytes4 occurenceSelector) {
    occurenceAddress = (address(Bytes.getBytes20(_blob, 0)));

    occurenceSelector = (Bytes.getBytes4(_blob, 20));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (TerrainMetadataData memory _table) {
    (_table.occurenceAddress, _table.occurenceSelector) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 objectTypeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 objectTypeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys (using the specified store).
   */
  function deleteRecord(IStore _store, bytes32 objectTypeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    _store.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(address occurenceAddress, bytes4 occurenceSelector) internal pure returns (bytes memory) {
    return abi.encodePacked(occurenceAddress, occurenceSelector);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    address occurenceAddress,
    bytes4 occurenceSelector
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(occurenceAddress, occurenceSelector);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 objectTypeId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = objectTypeId;

    return _keyTuple;
  }
}
