// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ExperienceMetadata, ExperienceMetadataData } from "./tables/ExperienceMetadata.sol";
import { ChipMetadata, ChipMetadataData } from "./tables/ChipMetadata.sol";
import { ChipNamespace } from "./tables/ChipNamespace.sol";
import { ChipAttachment } from "./tables/ChipAttachment.sol";
import { ExchangeChest, ExchangeChestData } from "./tables/ExchangeChest.sol";
import { ChestMetadata, ChestMetadataData } from "./tables/ChestMetadata.sol";
import { FFMetadata, FFMetadataData } from "./tables/FFMetadata.sol";
import { GateApprovals, GateApprovalsData } from "./tables/GateApprovals.sol";
import { ForceFieldApprovals, ForceFieldApprovalsData } from "./tables/ForceFieldApprovals.sol";
import { DisplayStatus } from "./tables/DisplayStatus.sol";
import { DisplayRegisterMsg } from "./tables/DisplayRegisterMsg.sol";
import { DisplayUnregisterMsg } from "./tables/DisplayUnregisterMsg.sol";
import { Notification, NotificationData } from "./tables/Notification.sol";
import { ItemShopNotif, ItemShopNotifData } from "./tables/ItemShopNotif.sol";
import { ExchangeChestNotif, ExchangeChestNotifData } from "./tables/ExchangeChestNotif.sol";
import { Players } from "./tables/Players.sol";
import { Areas, AreasData } from "./tables/Areas.sol";
import { Builds, BuildsData } from "./tables/Builds.sol";
import { BuildsWithPos, BuildsWithPosData } from "./tables/BuildsWithPos.sol";
import { Countdown, CountdownData } from "./tables/Countdown.sol";
import { Tokens } from "./tables/Tokens.sol";
import { NFTs } from "./tables/NFTs.sol";
import { ERC20Metadata, ERC20MetadataData } from "./tables/ERC20Metadata.sol";
import { ERC721Metadata, ERC721MetadataData } from "./tables/ERC721Metadata.sol";
import { ItemShop, ItemShopData } from "./tables/ItemShop.sol";
