// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ExperienceMetadata, ExperienceMetadataData } from "./tables/ExperienceMetadata.sol";
import { ChipMetadata, ChipMetadataData } from "./tables/ChipMetadata.sol";
import { ChipAttachment } from "./tables/ChipAttachment.sol";
import { ItemShop, ItemShopData } from "./tables/ItemShop.sol";
import { ChestMetadata, ChestMetadataData } from "./tables/ChestMetadata.sol";
import { FFMetadata, FFMetadataData } from "./tables/FFMetadata.sol";
import { ForceFieldApprovals, ForceFieldApprovalsData } from "./tables/ForceFieldApprovals.sol";
import { DisplayStatus } from "./tables/DisplayStatus.sol";
import { DisplayRegisterMsg } from "./tables/DisplayRegisterMsg.sol";
import { DisplayUnregisterMsg } from "./tables/DisplayUnregisterMsg.sol";
import { Notification, NotificationData } from "./tables/Notification.sol";
import { ItemShopNotif, ItemShopNotifData } from "./tables/ItemShopNotif.sol";
import { Players } from "./tables/Players.sol";
import { Areas, AreasData } from "./tables/Areas.sol";
import { Builds, BuildsData } from "./tables/Builds.sol";
import { BuildsWithPos, BuildsWithPosData } from "./tables/BuildsWithPos.sol";
import { Countdown, CountdownData } from "./tables/Countdown.sol";
import { Tokens } from "./tables/Tokens.sol";
import { NFTs } from "./tables/NFTs.sol";
import { TokenMetadata, TokenMetadataData } from "./tables/TokenMetadata.sol";
import { NFTMetadata, NFTMetadataData } from "./tables/NFTMetadata.sol";
import { Quest, QuestData } from "./tables/Quest.sol";
import { BaseTrigger, BaseTriggerData } from "./tables/BaseTrigger.sol";
import { LeafTrigger, LeafTriggerData } from "./tables/LeafTrigger.sol";
import { MapBeamTrigger, MapBeamTriggerData } from "./tables/MapBeamTrigger.sol";
import { EventTrigger, EventTriggerData } from "./tables/EventTrigger.sol";
import { ChallengeCompleteTrigger } from "./tables/ChallengeCompleteTrigger.sol";
import { CollectTrigger, CollectTriggerData } from "./tables/CollectTrigger.sol";
import { BasePredicate, BasePredicateData } from "./tables/BasePredicate.sol";
import { LeafPredicate, LeafPredicateData } from "./tables/LeafPredicate.sol";
