// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct PipeAccessData {
  bool depositAllowed;
  bool withdrawAllowed;
}

library PipeAccess {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "experience", name: "PipeAccess", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462657870657269656e63650000000050697065416363657373000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0002020001010000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, bytes32)
  Schema constant _keySchema = Schema.wrap(0x004002005f5f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bool, bool)
  Schema constant _valueSchema = Schema.wrap(0x0002020060600000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "targetEntityId";
    keyNames[1] = "callerEntityId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "depositAllowed";
    fieldNames[1] = "withdrawAllowed";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config (using the specified store).
   */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get depositAllowed.
   */
  function getDepositAllowed(
    bytes32 targetEntityId,
    bytes32 callerEntityId
  ) internal view returns (bool depositAllowed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get depositAllowed.
   */
  function _getDepositAllowed(
    bytes32 targetEntityId,
    bytes32 callerEntityId
  ) internal view returns (bool depositAllowed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get depositAllowed (using the specified store).
   */
  function getDepositAllowed(
    IStore _store,
    bytes32 targetEntityId,
    bytes32 callerEntityId
  ) internal view returns (bool depositAllowed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set depositAllowed.
   */
  function setDepositAllowed(bytes32 targetEntityId, bytes32 callerEntityId, bool depositAllowed) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((depositAllowed)), _fieldLayout);
  }

  /**
   * @notice Set depositAllowed.
   */
  function _setDepositAllowed(bytes32 targetEntityId, bytes32 callerEntityId, bool depositAllowed) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((depositAllowed)), _fieldLayout);
  }

  /**
   * @notice Set depositAllowed (using the specified store).
   */
  function setDepositAllowed(
    IStore _store,
    bytes32 targetEntityId,
    bytes32 callerEntityId,
    bool depositAllowed
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    _store.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((depositAllowed)), _fieldLayout);
  }

  /**
   * @notice Get withdrawAllowed.
   */
  function getWithdrawAllowed(
    bytes32 targetEntityId,
    bytes32 callerEntityId
  ) internal view returns (bool withdrawAllowed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get withdrawAllowed.
   */
  function _getWithdrawAllowed(
    bytes32 targetEntityId,
    bytes32 callerEntityId
  ) internal view returns (bool withdrawAllowed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get withdrawAllowed (using the specified store).
   */
  function getWithdrawAllowed(
    IStore _store,
    bytes32 targetEntityId,
    bytes32 callerEntityId
  ) internal view returns (bool withdrawAllowed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set withdrawAllowed.
   */
  function setWithdrawAllowed(bytes32 targetEntityId, bytes32 callerEntityId, bool withdrawAllowed) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((withdrawAllowed)), _fieldLayout);
  }

  /**
   * @notice Set withdrawAllowed.
   */
  function _setWithdrawAllowed(bytes32 targetEntityId, bytes32 callerEntityId, bool withdrawAllowed) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((withdrawAllowed)), _fieldLayout);
  }

  /**
   * @notice Set withdrawAllowed (using the specified store).
   */
  function setWithdrawAllowed(
    IStore _store,
    bytes32 targetEntityId,
    bytes32 callerEntityId,
    bool withdrawAllowed
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    _store.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((withdrawAllowed)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 targetEntityId, bytes32 callerEntityId) internal view returns (PipeAccessData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 targetEntityId, bytes32 callerEntityId) internal view returns (PipeAccessData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data (using the specified store).
   */
  function get(
    IStore _store,
    bytes32 targetEntityId,
    bytes32 callerEntityId
  ) internal view returns (PipeAccessData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = _store.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 targetEntityId, bytes32 callerEntityId, bool depositAllowed, bool withdrawAllowed) internal {
    bytes memory _staticData = encodeStatic(depositAllowed, withdrawAllowed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 targetEntityId, bytes32 callerEntityId, bool depositAllowed, bool withdrawAllowed) internal {
    bytes memory _staticData = encodeStatic(depositAllowed, withdrawAllowed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values (using the specified store).
   */
  function set(
    IStore _store,
    bytes32 targetEntityId,
    bytes32 callerEntityId,
    bool depositAllowed,
    bool withdrawAllowed
  ) internal {
    bytes memory _staticData = encodeStatic(depositAllowed, withdrawAllowed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    _store.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 targetEntityId, bytes32 callerEntityId, PipeAccessData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.depositAllowed, _table.withdrawAllowed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 targetEntityId, bytes32 callerEntityId, PipeAccessData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.depositAllowed, _table.withdrawAllowed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct (using the specified store).
   */
  function set(IStore _store, bytes32 targetEntityId, bytes32 callerEntityId, PipeAccessData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.depositAllowed, _table.withdrawAllowed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    _store.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (bool depositAllowed, bool withdrawAllowed) {
    depositAllowed = (_toBool(uint8(Bytes.getBytes1(_blob, 0))));

    withdrawAllowed = (_toBool(uint8(Bytes.getBytes1(_blob, 1))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (PipeAccessData memory _table) {
    (_table.depositAllowed, _table.withdrawAllowed) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 targetEntityId, bytes32 callerEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 targetEntityId, bytes32 callerEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys (using the specified store).
   */
  function deleteRecord(IStore _store, bytes32 targetEntityId, bytes32 callerEntityId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    _store.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(bool depositAllowed, bool withdrawAllowed) internal pure returns (bytes memory) {
    return abi.encodePacked(depositAllowed, withdrawAllowed);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bool depositAllowed,
    bool withdrawAllowed
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(depositAllowed, withdrawAllowed);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 targetEntityId, bytes32 callerEntityId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntityId;
    _keyTuple[1] = callerEntityId;

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
