// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../EntityId.sol";
import { Vec3 } from "../../Vec3.sol";

/**
 * @title IBedSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBedSystem {
  function removeDeadPlayerFromBed(EntityId playerEntityId, Vec3 dropCoord) external;

  function sleep(EntityId bedEntityId, bytes calldata extraData) external;

  function wakeup(Vec3 spawnCoord, bytes calldata extraData) external;
}
