// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ObjectTypeId } from "../../ObjectTypeIds.sol";
import { VoxelCoord } from "../../VoxelCoord.sol";
import { Direction } from "../common.sol";
import { EntityId } from "../../EntityId.sol";

/**
 * @title IBuildSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBuildSystem {
  function buildWithExtraData(
    ObjectTypeId buildObjectTypeId,
    VoxelCoord memory baseCoord,
    Direction direction,
    bytes memory extraData
  ) external payable returns (EntityId);

  function jumpBuildWithExtraData(
    ObjectTypeId buildObjectTypeId,
    Direction direction,
    bytes memory extraData
  ) external payable;

  function jumpBuild(ObjectTypeId buildObjectTypeId, Direction direction) external payable;

  function jumpBuild(ObjectTypeId buildObjectTypeId) external payable;

  function build(
    ObjectTypeId buildObjectTypeId,
    VoxelCoord memory baseCoord,
    Direction direction
  ) external payable returns (EntityId);

  function build(ObjectTypeId buildObjectTypeId, VoxelCoord memory baseCoord) external payable returns (EntityId);
}
