// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../EntityId.sol";
import { ObjectType } from "../../ObjectType.sol";

/**
 * @title ICraftSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICraftSystem {
  function craft(EntityId stationEntityId, ObjectType[] memory inputTypes, uint16[] memory inputAmounts) external;
}
