// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { DisplayContent } from "./../../Types.sol";

/**
 * @title IDisplaySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDisplaySystem {
  function getDisplayContent(bytes32 entityId) external view returns (DisplayContent memory);
}
