// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../EntityId.sol";
import { DisplayContentData } from "../tables/DisplayContent.sol";

/**
 * @title IDisplaySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDisplaySystem {
  function getDisplayContent(EntityId entityId) external view returns (DisplayContentData memory);

  function setDisplayContent(EntityId entityId, DisplayContentData memory content) external;
}
