// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ObjectTypeId } from "../../ObjectTypeIds.sol";
import { Vec3 } from "../../Vec3.sol";
import { EntityId } from "../../EntityId.sol";

/**
 * @title IDropSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDropSystem {
  function drop(ObjectTypeId dropObjectTypeId, uint16 numToDrop, Vec3 coord) external;

  function dropTool(EntityId toolEntityId, Vec3 coord) external;

  function dropTools(EntityId[] memory toolEntityIds, Vec3 coord) external;
}
