// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Vec3 } from "../../Vec3.sol";
import { ObjectTypeId } from "../../ObjectTypeId.sol";
import { EntityId } from "../../EntityId.sol";

/**
 * @title IMineSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMineSystem {
  function getRandomOreType(Vec3 coord) external view returns (ObjectTypeId);

  function mineWithTool(
    EntityId caller,
    Vec3 coord,
    uint16 toolSlot,
    bytes calldata extraData
  ) external returns (EntityId);

  function mine(EntityId caller, Vec3 coord, bytes calldata extraData) external returns (EntityId);

  function mineUntilDestroyed(EntityId caller, Vec3 coord, uint16 toolSlot, bytes calldata extraData) external payable;

  function mineUntilDestroyed(EntityId caller, Vec3 coord, bytes calldata extraData) external payable;
}
