// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../EntityId.sol";
import { Vec3 } from "../../Vec3.sol";
import { Direction } from "../common.sol";

/**
 * @title IMoveSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMoveSystem {
  function move(EntityId callerEntityId, Vec3[] memory newCoords) external;

  function moveDirections(EntityId callerEntityId, Direction[] memory directions) external;
}
