// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TransferData, PipeTransferData } from "./../../Types.sol";

/**
 * @title IMultiTransferSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMultiTransferSystem {
  function transferWithPipesWithExtraData(
    bytes32 srcEntityId,
    bytes32 dstEntityId,
    TransferData memory transferData,
    PipeTransferData[] memory pipesTransferData,
    bytes memory extraData
  ) external payable;

  function transferWithPipes(
    bytes32 srcEntityId,
    bytes32 dstEntityId,
    TransferData memory transferData,
    PipeTransferData[] memory pipesTransferData
  ) external payable;
}
