// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../EntityId.sol";
import { Vec3 } from "../../Vec3.sol";
import { ObjectTypeId } from "../../ObjectTypeId.sol";
import { ObjectAmount } from "../../ObjectTypeLib.sol";

/**
 * @title IPickupSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPickupSystem {
  function pickupAll(EntityId callerEntityId, Vec3 coord) external;

  function pickup(EntityId callerEntityId, ObjectTypeId pickupObjectTypeId, uint16 numToPickup, Vec3 coord) external;

  function pickupTool(EntityId callerEntityId, EntityId toolEntityId, Vec3 coord) external;

  function pickupMultiple(
    EntityId callerEntityId,
    ObjectAmount[] memory pickupObjects,
    EntityId[] memory pickupTools,
    Vec3 coord
  ) external;
}
