// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../EntityId.sol";
import { VoxelCoord, PipeTransferData, PipeTransferCommonContext } from "../../Types.sol";

/**
 * @title IPipeTransferHelperSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPipeTransferHelperSystem {
  function pipeTransferCommon(
    EntityId callerEntityId,
    uint16 callerObjectTypeId,
    VoxelCoord memory callerCoord,
    bool isDeposit,
    PipeTransferData memory pipeTransferData
  ) external payable returns (PipeTransferCommonContext memory);
}
