// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "../../EntityId.sol";
import { ObjectTypeId } from "../../ObjectTypeId.sol";

/**
 * @title ITransferSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITransferSystem {
  function transfer(
    EntityId callerEntityId,
    EntityId fromEntityId,
    EntityId toEntityId,
    ObjectTypeId transferObjectTypeId,
    uint16 numToTransfer,
    bytes calldata extraData
  ) external payable;

  function transferTool(
    EntityId callerEntityId,
    EntityId fromEntityId,
    EntityId toEntityId,
    EntityId toolEntityId,
    bytes calldata extraData
  ) external payable;

  function transferTools(
    EntityId callerEntityId,
    EntityId fromEntityId,
    EntityId toEntityId,
    EntityId[] memory toolEntityIds,
    bytes calldata extraData
  ) external payable;
}
