// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ObjectTypeId } from "./ObjectTypeId.sol";
import { ObjectTypes } from "./ObjectTypes.sol";

function timeToGrow(ObjectTypeId objectTypeId) pure returns (uint128) {
  if (objectTypeId == ObjectTypes.WheatSeed) {
    return 10 seconds;
  }

  return 0;
}
