// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { ObjectTypeId } from "../../ObjectTypeIds.sol";

library ObjectTypeOreAmount {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "ObjectTypeOreAmo", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746200000000000000000000000000004f626a656374547970654f7265416d6f);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0002010002000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint16, uint16)
  Schema constant _keySchema = Schema.wrap(0x0004020001010000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint16)
  Schema constant _valueSchema = Schema.wrap(0x0002010001000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "objectTypeId";
    keyNames[1] = "oreTypeId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "amount";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get amount.
   */
  function getAmount(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId) internal view returns (uint16 amount) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get amount.
   */
  function _getAmount(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId) internal view returns (uint16 amount) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get amount.
   */
  function get(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId) internal view returns (uint16 amount) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get amount.
   */
  function _get(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId) internal view returns (uint16 amount) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Set amount.
   */
  function setAmount(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId, uint16 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Set amount.
   */
  function _setAmount(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId, uint16 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Set amount.
   */
  function set(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId, uint16 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Set amount.
   */
  function _set(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId, uint16 amount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((amount)), _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint16 amount) internal pure returns (bytes memory) {
    return abi.encodePacked(amount);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(uint16 amount) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(amount);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(ObjectTypeId objectTypeId, ObjectTypeId oreTypeId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(ObjectTypeId.unwrap(objectTypeId)));
    _keyTuple[1] = bytes32(uint256(ObjectTypeId.unwrap(oreTypeId)));

    return _keyTuple;
  }
}
