// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum Action {
  None,
  Build,
  Mine,
  Move,
  Craft,
  Drop,
  Pickup,
  Transfer,
  Spawn,
  Sleep,
  Wakeup,
  FuelMachine,
  HitMachine,
  AttachProgram,
  DetachProgram,
  AddFragment,
  RemoveFragment,
  Death
}

enum Direction {
  PositiveX,
  NegativeX,
  PositiveY,
  NegativeY,
  PositiveZ,
  NegativeZ,
  PositiveXPositiveY,
  PositiveXNegativeY,
  NegativeXPositiveY,
  NegativeXNegativeY,
  PositiveXPositiveZ,
  PositiveXNegativeZ,
  NegativeXPositiveZ,
  NegativeXNegativeZ,
  PositiveYPositiveZ,
  PositiveYNegativeZ,
  NegativeYPositiveZ,
  NegativeYNegativeZ,
  PositiveXPositiveYPositiveZ,
  PositiveXPositiveYNegativeZ,
  PositiveXNegativeYPositiveZ,
  PositiveXNegativeYNegativeZ,
  NegativeXPositiveYPositiveZ,
  NegativeXPositiveYNegativeZ,
  NegativeXNegativeYPositiveZ,
  NegativeXNegativeYNegativeZ
}
