// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { WorldMetadata, WorldMetadataData } from "./tables/WorldMetadata.sol";
import { UniqueEntity } from "./tables/UniqueEntity.sol";
import { ObjectTypeMetadata, ObjectTypeMetadataData } from "./tables/ObjectTypeMetadata.sol";
import { Recipes, RecipesData } from "./tables/Recipes.sol";
import { Terrain } from "./tables/Terrain.sol";
import { Spawn, SpawnData } from "./tables/Spawn.sol";
import { ObjectType } from "./tables/ObjectType.sol";
import { Position, PositionData } from "./tables/Position.sol";
import { ReversePosition } from "./tables/ReversePosition.sol";
import { LastKnownPosition, LastKnownPositionData } from "./tables/LastKnownPosition.sol";
import { Player } from "./tables/Player.sol";
import { ReversePlayer } from "./tables/ReversePlayer.sol";
import { PlayerMetadata, PlayerMetadataData } from "./tables/PlayerMetadata.sol";
import { PlayerActivity } from "./tables/PlayerActivity.sol";
import { InventoryTool } from "./tables/InventoryTool.sol";
import { ReverseInventoryTool } from "./tables/ReverseInventoryTool.sol";
import { InventoryCount } from "./tables/InventoryCount.sol";
import { InventoryObjects } from "./tables/InventoryObjects.sol";
import { InventorySlots } from "./tables/InventorySlots.sol";
import { ItemMetadata } from "./tables/ItemMetadata.sol";
import { BlockMetadata } from "./tables/BlockMetadata.sol";
import { Equipped } from "./tables/Equipped.sol";
import { ExperiencePoints } from "./tables/ExperiencePoints.sol";
import { Health, HealthData } from "./tables/Health.sol";
import { Stamina, StaminaData } from "./tables/Stamina.sol";
