// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { App } from "./tables/App.sol";
import { ProgramEntity } from "./tables/ProgramEntity.sol";
