// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ChestMetadataData } from "../tables/ChestMetadata.sol";

/**
 * @title IChestMetadataSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IChestMetadataSystem {
  function experience__setChestMetadata(bytes32 entityId, ChestMetadataData memory metadata) external;

  function experience__setChestName(bytes32 entityId, string memory name) external;

  function experience__setChestDescription(bytes32 entityId, string memory description) external;

  function experience__deleteChestMetadata(bytes32 entityId) external;
}
