// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityId } from "@biomesaw/world/src/EntityId.sol";

/**
 * @title IChipAdminSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IChipAdminSystem {
  function experience__setChipAdmin(EntityId entityId, address admin) external;

  function experience__deleteChipAdmin(EntityId entityId) external;
}
