// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IChipAdminSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IChipAdminSystem {
  function experience__setChipAdmin(bytes32 entityId, address admin) external;

  function experience__deleteChipAdmin(bytes32 entityId) external;
}
