// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ShopData } from "./../tables/Shop.sol";

/**
 * @title IShopSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IShopSystem {
  function experience__setShop(bytes32 entityId, ShopData memory shopData) external;

  function experience__deleteShop(bytes32 entityId) external;

  function experience__setBuyShop(bytes32 entityId, uint8 buyObjectTypeId, uint256 buyPrice) external;

  function experience__setSellShop(bytes32 entityId, uint8 sellObjectTypeId, uint256 sellPrice) external;

  function experience__setShopBalance(bytes32 entityId, uint256 balance) external;
}
