// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IInitHandBlocksSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInitHandBlocksSystem {
  function initHandcraftedObjectTypes() external;

  function initHandcrafedRecipes() external;
}
