// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IInitInteractablesSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInitInteractablesSystem {
  function initInteractableObjectTypes() external;

  function initInteractablesRecipes() external;
}
