// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { VoxelCoord } from "@everlonxyz/utils/src/Types.sol";

/**
 * @title ITerrainSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITerrainSystem {
  function Air(VoxelCoord memory coord) external view returns (bytes32);

  function Trees(VoxelCoord memory coord) external view returns (bytes32);

  function Flora(VoxelCoord memory coord) external view returns (bytes32);

  function TerrainBlocks(VoxelCoord memory coord) external view returns (bytes32);
}
