// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RegionMerkleRoot } from "../src/codegen/tables/RegionMerkleRoot.sol";

function initTerrain() {
  RegionMerkleRoot.set(0, 0, hex"a411b0e5e60946651eebea32bcd98e14c76f0264e26eef050a9848bc34919855");
}
