// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RegionMerkleRoot } from "../src/codegen/tables/RegionMerkleRoot.sol";

contract InitTerrain {
  function initTerrain() internal {
    RegionMerkleRoot.set(0, 0, hex"c1c4fe1f0a8c848f4cd987943cb74607cce09655dd1650a49502e347a0d76e27");
  }
}
